gems: [jekyll-paginate]

# Dependencies
markdown:            kramdown
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Dave Poon
tagline:             ' / Thoughts and Ramblings'
description:         '<a href="https://twitter.com/davepoon" target="_blank">@davepoon</a> is a designer working and living in Sydney. Originally from Hong Kong. He design user interfaces, write codes, manage design teams and manage products. Co-Founder of  <a href="http://spikenode.com" target="_blank">http://spikenode.com</a>.'
url:                 http://blog.davepoon.net/
baseurl:             /
paginate:            1

# About/contact
author:
  name:              Dave Poon
  url:               https://twitter.com/davepoon
  email:             davepoon@davepoon.net

# Custom vars
version:             0.9.0

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:         public/_scss
  style:            :compressed
